sudo: false
dist: precise

language: php

notifications:
  email:
    on_success: never
    on_failure: change

branches:
  only:
    - master
    - /^[0-9]+.*$/

cache:
  directories:
    - $HOME/.composer/cache

env:
  matrix:
    - WP_VERSION=latest WP_MULTISITE=0
  global:
    - PLUGIN_SLUG=wenprise-wechatpay-checkout-for-woocommerce
    - SVN_REPO=https://plugins.svn.wordpress.org/$PLUGIN_SLUG/
    - GIT_REPO=https://github.com/iwillhappy1314/$PLUGIN_SLUG.git
    - MAINFILE="$PLUGIN_SLUG.php"
    - "Az4DaT9b4rvOYoQ12b8FRiU1W4ROd1ltNdokOamxUm/rEb1l6a3tXrg1PynJ8GoAxUfgfxM3lBcrhCiICg4lBmQWjk96qCCRpiKW1K9/pFXtB7Rh582FHFSWLGop20bhXubVKiMKEXK6z0IACBRgY0k4AvMN4op6LpG/uGdi+fvyTZuzzhHW+xlVn3CKh736bUltXgTK3EthrUU+G9cMr79fUf1SqZ6ouwx08MzMSl6b13S5sipfF+iPj8wny0IKvm78NuoBS0KK5Sx08WTpTAVc23JoXpz3Fcd27cVtTLdH4lwCvZa4S1duFShXGLMq5HL+hOeH9qT/wH/9IndmSoHlkAIVOUlV/eo8uPK90SUdF/QQPQ/ajchu+PHWWkirfExQPOwfxQdowX33u5t09Zf+mRSaMovV6oX1oxptVP9nOCgry03ZKOHhFlRercEkNMqEL+4ad881/Gwyn8pgByNyi2mbwZJI0X0EmBsoIhPUzTHM7doVRMAzZv7tnihQZ//crbx4He+wSSSEJfKoLjYJ3z7lyWxQXfPmzVepXLNTrAZEQ6kf7WHjczsV7VKmKXbXfr+9uOpD1E4MNT+bAvK7t4Rak60ygxuDv7bweBQ5Pm3+pC9TOkJugmUbmnD9GvA46MUuxprX08PS/ljzHCuW3zaQ8GKZPYhwImR1LjI="

matrix:
  include:
    - php: 7.0
      env: WP_VERSION=latest WP_PULUGIN_DEPLOY=1
      dist: precise

before_script:
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - |
    if [ -f ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini ]; then
      phpenv config-rm xdebug.ini
    else
      echo "xdebug.ini does not exist"
    fi
  - |
    if [[ ! -z "$WP_VERSION" ]] ; then
      bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
      composer global require "phpunit/phpunit=4.8.*|5.7.*"
    fi
  - |
    if [[ "$WP_TRAVISCI" == "phpcs" ]] ; then
      composer global require wp-coding-standards/wpcs
      phpcs --config-set installed_paths $HOME/.composer/vendor/wp-coding-standards/wpcs
    fi

script:
  - |
    if [[ ! -z "$WP_VERSION" ]] ; then
      phpunit
      WP_MULTISITE=1 phpunit
    fi
  - |
    if [[ "$WP_TRAVISCI" == "phpcs" ]] ; then
      phpcs
    fi

after_success: curl -L https://raw.githubusercontent.com/iwillhappy1314/deploy2wporg/master/deploy.sh | sh